### ISSUE TITLE
Solution for GetPathArray function to return correct data

### ISSUE THREAD

**Issue by drabadan** [Crome696/ScriptSDK#8]
`namespace StealthAPI
{
    [StructLayout(LayoutKind.Sequential, Pack = 1)]
    public struct MyPoint
    {
        public ushort X;
        public ushort Y;
        public sbyte Z;
    }
}`

StealthClient from 299 line
`else
                        {
                            uint itemCount;
                            switch (type)
                            {
                                case PacketType.SCReadStaticsXY:
                                case PacketType.SCGetBuffBarInfo:
                                    itemCount = barray[0];
                                    barray = barray.Skip(1).ToArray();
                                    break;
                                case PacketType.SCGetPathArray:
                                    itemCount = barray[0];
                                    //barray = barray.Skip(2).ToArray();
                                    break;
                                default:
                                    itemCount = BitConverter.ToUInt32(barray, 0);
                                    barray = barray.Skip(4).ToArray();
                                    break;
                            }
`

**Comment by Crome696** [comment]
Please make a pull request then i gladly will add it to our source :)

**Comment by Crome696** [comment]
Request has been pulled! Thanks for your support!
